<?php

$default_options = array(
	'rcno_settings_version'    => '1.0.0',
	'rcno_review_slug'         => 'review',
	'rcno_reviews_archive'     => 'archive_display_excerpt',
	'rcno_reviews_on_homepage' => '1',
	'rcno_reviews_in_rss'      => '1',
	'rcno_reviews_in_rest'     => '1',
	'rcno_taxonomy_selection'  => array(
		'author' => 'Author',
		'genre'  => 'Genre',
		'series' => 'Series',
	),
	'rcno_author_slug'         => 'author',
	'rcno_author_show'         => '1',
	'rcno_genre_slug'          => 'genre',
	'rcno_genre_hierarchical'  => '1',
	'rcno_genre_show'          => '1',
	'rcno_series_slug'         => 'series',
	'rcno_series_hierarchical' => '1',
	'rcno_series_show'         => '1',
	'rcno_show_isbn'           => '1',
	'rcno_show_isbn13'         => '1',
	'rcno_show_asin'           => '1',
	'rcno_show_gr_id'          => '1',
	'rcno_show_gr_url'         => '1',
	'rcno_show_publisher'      => '1',
	'rcno_show_pub_date'       => '1',
	'rcno_show_pub_format'     => '1',
	'rcno_show_pub_edition'    => '1',
	'rcno_show_page_count'     => '1',
	'rcno_show_gr_rating'      => '1',

	'rcno_show_review_score_box'            => '1',
	'rcno_show_review_score_box_background' => '#ffffff',
	'rcno_show_review_score_box_accent'     => '#0f0000',

	'rcno_show_book_slider_widget'    => '1',
	'rcno_show_recent_reviews_widget' => '1',
	'rcno_show_tag_cloud_widget'      => '1',
	'rcno_show_taxonomy_list_widget'  => '1',
	'rcno_review_template'            => 'rcno_default',
	'rcno_excerpt_read_more'          => 'Read more',
	'rcno_excerpt_word_count'         => '55',
);